from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, Sequence

from .diagnosis_schema import PredictionResult


ALLOWED_DERIVED_MEASURES = {
    "power_w",
    "temperature_gap_k",
    "overstrain_load",
}


class DiagnosisRuntimeRepositoryPort(Protocol):
    """Persistence/query boundary required by the Diagnosis runtime service."""

    def resolve_version(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_versions(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def selected_version_for_user(self, **kwargs: Any) -> str | None: ...
    def save_selected_version(self, **kwargs: Any) -> None: ...
    def latest_result_rows(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def snapshot_drilldown(self, **kwargs: Any) -> dict[str, Any] | None: ...
    def timeline_rows(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def observation_bounds(self, **kwargs: Any) -> tuple[datetime, datetime]: ...
    def observation_rows(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def nearest_timeline_rows(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def nearest_sensor_time(self, **kwargs: Any) -> datetime | None: ...
    def observations_at(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def latest_artifact_references(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def dashboard_support_rows(self, **kwargs: Any) -> dict[str, Any]: ...
    def create_session(self, **kwargs: Any) -> dict[str, Any]: ...
    def session(self, **kwargs: Any) -> dict[str, Any] | None: ...
    def update_session(self, **kwargs: Any) -> dict[str, Any]: ...


class PredictionResultRepositoryPort(Protocol):
    def save(self, result: PredictionResult) -> PredictionResult: ...
    def get(self, prediction_id: str, **kwargs: Any) -> PredictionResult | None: ...
    def list(self, **kwargs: Any) -> Sequence[PredictionResult]: ...


class EquipmentSnapshotQueryPort(Protocol):
    """Inbound port; implemented by Equipment without importing its implementation."""

    def current_equipment(self, equipment_id: str, **scope: Any) -> dict[str, Any]: ...


class ObservationDatasetQueryPort(Protocol):
    """Inbound port; implemented by Dataset for governed observation reads."""

    def observations(self, *, dataset_version_id: str, **query: Any) -> Sequence[dict[str, Any]]: ...


__all__ = [
    "ALLOWED_DERIVED_MEASURES",
    "DiagnosisRuntimeRepositoryPort",
    "EquipmentSnapshotQueryPort",
    "ObservationDatasetQueryPort",
    "PredictionResultRepositoryPort",
]
