import {test,expect} from '@playwright/test';
import {text} from '../src/standalone/presentation.js';
const path='/factory-status-original/index.html';
async function ready(page:any){await page.waitForFunction(()=>{const s=(window as any).factoryState;return s?.lineage||s?.workflowError||s?.error;});expect(await page.evaluate(()=>(window as any).factoryState.error)).toBeNull();}
async function login(page:any,name='manager',password='Manager'){expect((await page.request.post('/api/auth/login',{data:{email:`${name}@ontology.local`,password:`${password}!2026`}})).ok()).toBeTruthy();}
test('real PG: default entry and login redirect without iframe',async({page})=>{await page.goto('/');await expect(page).toHaveURL(/\/login\?/);await page.getByLabel('이메일',{exact:true}).fill('manager@ontology.local');await page.getByLabel('비밀번호',{exact:true}).fill('Manager!2026');await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page).toHaveURL(/factory-status-original/);await ready(page);expect(await page.locator('iframe').count()).toBe(0);});
for(const [name,password,role] of [['manager','Manager','process_manager'],['engineer','Engineer','process_engineer'],['technician','Technician','maintenance_technician']])test(`real PG: ${role} tabs do not grant permissions`,async({page})=>{await login(page,name,password);await page.goto(path);await ready(page);expect(await page.evaluate(()=>(window as any).factoryState.role)).toBe(role);let writes=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/maintenance/'))writes++;});await page.getByRole('button',{name:/보전팀 · 작업 큐/}).click();await page.getByRole('button',{name:/생산관리자 · 오늘/}).click();expect(await page.evaluate(()=>(window as any).factoryState.role)).toBe(role);expect(await page.evaluate(()=>(window as any).factoryState.command)).toBeNull();expect(writes).toBe(0);await page.screenshot({path:`../../docs/eval/standalone-page-2026-09-06/${role}.png`});});
test('real PG: asset/snapshot reload/direct URL and side view',async({page})=>{await login(page);await page.goto(path);await ready(page);const a=await page.evaluate(()=>(window as any).factoryState.model.assets[1]);await page.getByTitle(text(a.displayName),{exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).factoryState.detail?.event.assetId)).toBe(a.assetId);await page.getByTitle(text(a.displayName),{exact:true}).click();await expect(page.getByRole('heading',{name:'정비 · 생산 현황',exact:true})).toBeVisible();await expect(page.locator('#dc-root [title^="근거 산출물"]')).toHaveCount(1);await expect(page.locator('#dc-root')).not.toContainText('서버 저장 완료');await expect(page.locator('#dc-root')).not.toContainText('넘김 완료');await page.screenshot({path:'../../docs/eval/standalone-page-2026-09-06/sideview.png'});const url=page.url();expect(url).toContain('snapshot=');expect(url).toContain('asof=');await page.reload();await ready(page);expect(await page.evaluate(()=>(window as any).factoryState.selectedAssetId)).toBe(a.assetId);await page.goto(url);await ready(page);expect(await page.evaluate(()=>(window as any).factoryState.detail.event.assetId)).toBe(a.assetId);});
test('real PG: wrong URL snapshot held and React route retained',async({page})=>{await login(page);await page.goto(path);await ready(page);const u=new URL(page.url());u.searchParams.set('snapshot','wrong');await page.goto(u.href);await page.waitForFunction(()=>(window as any).factoryState.error);expect(await page.evaluate(()=>(window as any).factoryState.command)).toBeNull();expect(await page.evaluate(()=>(window as any).factoryState.error)).toContain('snapshot');await page.goto('/app/projects/manufacturing-demo-project/operations');await expect(page).toHaveURL(/\/app\/projects/);expect(await page.locator('#root').count()).toBe(1);});
test('fault injection: late response cannot replace newer asset',async({page})=>{await login(page);await page.goto(path);await ready(page);const aa=await page.evaluate(()=>(window as any).factoryState.model.assets.slice(1,3));await page.route('**/detail-view?**',async r=>{if(r.request().url().includes(encodeURIComponent(aa[0].assetId)))await new Promise(resolve=>setTimeout(resolve,900));await r.continue().catch(()=>{});});await page.getByTitle(text(aa[0].displayName),{exact:true}).click();await page.getByTitle(text(aa[1].displayName),{exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).factoryState.detail?.event.assetId)).toBe(aa[1].assetId);await page.waitForTimeout(1100);expect(await page.evaluate(()=>(window as any).factoryState.detail.event.assetId)).toBe(aa[1].assetId);});
for(const status of [200,409])test(`mock workflow only: save ${status}, duplicate click and requery`,async({page})=>{
 await login(page);let posts=0,reads=0,saved=false;
 await page.route('**/detail-view?**',async route=>{reads++;const r=await route.fetch();const v=await r.json();v.closed_loop={work_orders:[],inspection_results:[],maintenance_actions:[],maintenance_events:[],activities:[],available_actions:saved?[]:[{action_id:'approve_maintenance_work_order',target_id:'MOCK-WO',disabled_reason:null}],runtime_status:null};await route.fulfill({json:v});});
 await page.route('**/maintenance/events/**/lineage',async route=>{const r=await route.fetch();const v=await r.json();v.recommendations=[];v.work_orders=[{work_order_id:'MOCK-WO',work_type:'maintenance',status:saved?'approved':'requested'}];await route.fulfill({json:v});});
 await page.route('**/maintenance-work-orders/MOCK-WO/approve',async route=>{posts++;expect(route.request().headers()['idempotency-key']).toBeTruthy();expect(route.request().headers()['x-csrf-token']).toBeTruthy();await new Promise(r=>setTimeout(r,200));saved=status===200;await route.fulfill({status,json:status===200?{work_order_id:'MOCK-WO'}:{detail:'state_conflict'}});});
 await page.goto(path);await page.waitForFunction(()=>(window as any).factoryState.command);const before=reads;
 await page.evaluate(()=>{const s=(window as any).factoryState;const detail={type:'operations:command',assetId:s.selectedAssetId,eventId:s.selectedEventId,snapshotBasis:s.detail.snapshotBasis,command:s.command};window.dispatchEvent(new CustomEvent('factory:request',{detail}));window.dispatchEvent(new CustomEvent('factory:request',{detail}));});
 await expect.poll(()=>posts).toBe(1);await expect.poll(()=>page.evaluate(()=>(window as any).factoryState.busy)).toBe(false);
 if(status===200){await expect.poll(()=>page.evaluate(()=>(window as any).factoryState.notice)).toContain('재조회 완료');expect(reads).toBeGreaterThan(before+1);expect(await page.evaluate(()=>(window as any).factoryState.notice)).toContain('재조회 완료');await page.reload();await ready(page);expect(await page.evaluate(()=>(window as any).factoryState.command)).toBeNull();}
 else{expect(await page.evaluate(()=>(window as any).factoryState.workflowError)).toContain('409');expect(await page.evaluate(()=>(window as any).factoryState.notice)).toBeNull();}
});

test('real PG: Korean signal history and field values reach rendered UI',async({page})=>{
 await login(page,'engineer','Engineer');await page.goto(path);await ready(page);
 const evidence=await page.evaluate(()=>{const s=(window as any).factoryState;return {risk:s.detail.event.failureProbability,history:s.detail.sensors.filter((x:any)=>x.historyPoints.length).length};});
 expect(evidence.history).toBeGreaterThan(0);await expect(page.locator('#dc-root')).toContainText('마지막 정비 경과');await expect(page.locator('#dc-root')).toContainText('설비 중요도');await expect(page.locator('#dc-root')).toContainText('공기압축기 1호');await expect(page.locator('#dc-root')).toContainText('전압');await expect(page.locator('#dc-root')).toContainText('최근 관측');await expect(page.locator('#dc-root')).toContainText('위험 증가 방향');await expect(page.locator('#dc-root')).not.toContainText('failure_risk');await expect(page.locator('#dc-root')).not.toContainText('model unit');await expect(page.locator('#dc-root')).not.toContainText('rotation raw');
 await page.screenshot({path:'../../docs/eval/standalone-page-2026-09-06/mapping-engineer.png',fullPage:true});
});

test('real PG: runtime context and persisted maintenance reach selected detail',async({page})=>{
 await login(page,'engineer','Engineer');await page.goto(path);await ready(page);
 const s=await page.evaluate(()=>{const x=(window as any).factoryState;return {error:x.contextError,context:x.contextRead,maintenance:x.detail.maintenanceContext,history:x.detail.equipmentHistory};});
 expect(s.error).toBeNull();expect(s.context.identity.asset_id).toBe('CMP-S03-L03-01');expect(s.maintenance.lastMaintenanceDaysAgo).toBe(20);expect(s.history).toHaveLength(1);expect(s.maintenance.openWorkOrderExists).toBe(false);await expect(page.locator('#dc-root')).toContainText('20일');
});
