"""Idempotent Canonical V3.1 bootstrap for the hosted demo environment.

The source snapshot is produced by ``Biz-CollabCraft/gen_data`` and contains
only canonical source/reference material needed for ingestion. Prediction and
Result Artifact fixtures from gen_data are deliberately not consumed here.
Product results are generated by backend diagnosis runtime inference.
"""

from __future__ import annotations

import hashlib
import json
import os
import uuid
from pathlib import Path
from typing import Any

from app.diagnosis.evidence import build_product_result_artifact
from app.diagnosis.predictor import configured_predictor

from .adapters import (
    BundleFileAdapter,
    PostgreSQLPredictiveMaintenanceBundleIngestor,
    PredictiveMaintenanceCanonicalV3SourceAdapter,
)
from .dependencies import database_target
from .domain_packs.predictive_maintenance import PredictiveMaintenanceOntologyMaterializer


ORGANIZATION_ID = "org-ontology-demo"
PROJECT_ID = "manufacturing-demo-project"
WORKSPACE_ID = "manufacturing-demo"
SOURCE_VERSION = "canonical-ai4i-physics-v3.1"
DEFAULT_SOURCE_ROOT = Path("/app/.source/gen_data")
OUTPUT_ROLES = {
    "prediction_snapshot",
    "prediction_factor",
    "prediction_timeline",
    "result_artifact",
}


def _postgres_modules():
    try:
        import psycopg
        from psycopg.rows import dict_row
        from psycopg.types.json import Jsonb
    except ImportError as exc:  # pragma: no cover - deployment packaging guard
        raise RuntimeError("demo predictive-maintenance bootstrap requires backend[postgres]") from exc
    return psycopg, dict_row, Jsonb


def _normalize_database_url(value: str) -> str:
    normalized = value.replace("postgresql+psycopg://", "postgresql://", 1)
    if not normalized.startswith("postgresql://"):
        raise ValueError("hosted predictive-maintenance bootstrap requires PostgreSQL")
    return normalized


def _set_scope(connection: Any) -> None:
    connection.execute("SELECT set_config('app.organization_id',%s,true)", (ORGANIZATION_ID,))
    connection.execute("SELECT set_config('app.project_id',%s,true)", (PROJECT_ID,))


def _runtime_candidates(connection: Any, dataset_version_id: str) -> list[dict[str, Any]]:
    """Select one high-signal observation per CNC without consulting hidden truth.

    Candidate selection uses only public canonical sensor fields. The selected
    observation is then passed through the backend-owned predictor; this query is
    not itself a prediction or a label lookup.
    """

    return list(
        connection.execute(
            """
            WITH scored AS (
                SELECT
                    o.*,
                    GREATEST(
                        o.tool_wear_min / 240.0,
                        (o.tool_wear_min * o.torque_nm) / 13000.0,
                        CASE
                            WHEN (o.torque_nm * o.rotational_speed_rpm * 2.0 * pi() / 60.0) < 3500.0
                            THEN 1.0 + (3500.0 - (o.torque_nm * o.rotational_speed_rpm * 2.0 * pi() / 60.0)) / 3500.0
                            WHEN (o.torque_nm * o.rotational_speed_rpm * 2.0 * pi() / 60.0) > 9000.0
                            THEN 1.0 + ((o.torque_nm * o.rotational_speed_rpm * 2.0 * pi() / 60.0) - 9000.0) / 9000.0
                            ELSE 0.0
                        END,
                        CASE
                            WHEN (o.process_temperature_k - o.air_temperature_k) < 8.6
                                 AND o.rotational_speed_rpm < 1380.0
                            THEN 1.0 + (8.6 - (o.process_temperature_k - o.air_temperature_k))
                            ELSE 0.0
                        END
                    ) AS signal_rank
                FROM pm_cnc_observations o
                WHERE o.dataset_version_id=%s
            ), ranked AS (
                SELECT scored.*,
                       row_number() OVER (
                           PARTITION BY asset_id
                           ORDER BY signal_rank DESC, observed_at DESC
                       ) AS candidate_rank
                FROM scored
            )
            SELECT * FROM ranked
            WHERE candidate_rank=1
            ORDER BY asset_id
            """,
            (dataset_version_id,),
        ).fetchall()
    )


def _artifact_checksum(artifact: dict[str, Any]) -> str:
    rendered = json.dumps(
        artifact,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(rendered).hexdigest()


def _runtime_fixture(row: dict[str, Any]) -> dict[str, Any]:
    observed_at = row["observed_at"].isoformat()
    asset_id = str(row["asset_id"])
    return {
        "schema_version": "1.0",
        "event_id": f"runtime-{asset_id}-{observed_at}",
        "scenario_id": f"canonical-v3.1-runtime:{asset_id}",
        "dataset_version": SOURCE_VERSION,
        "asset_type": "cnc",
        "equipment": {
            "equipment_id": asset_id,
            # Source asset_master has no business criticality. Keep inference
            # neutral; product UI derives display criticality from result status.
            "criticality": "medium",
        },
        "observation": {
            "timestamp": observed_at,
            "product_type": row.get("product_type"),
            "air_temperature_k": float(row["air_temperature_k"]),
            "process_temperature_k": float(row["process_temperature_k"]),
            "rotational_speed_rpm": float(row["rotational_speed_rpm"]),
            "torque_nm": float(row["torque_nm"]),
            "tool_wear_min": float(row["tool_wear_min"]),
        },
        "history": [],
    }


def _materialize_runtime_results(database_url: str, dataset_version_id: str) -> dict[str, Any]:
    psycopg, dict_row, Jsonb = _postgres_modules()
    predictor = configured_predictor()
    with psycopg.connect(database_url, row_factory=dict_row) as connection:
        with connection.transaction():
            _set_scope(connection)
            connection.execute(
                "SELECT pg_advisory_xact_lock(hashtext(%s))",
                (f"demo-runtime:{PROJECT_ID}:{dataset_version_id}",),
            )
            roles = {
                str(row["role"])
                for row in connection.execute(
                    "SELECT role FROM dataset_files WHERE dataset_version_id=%s",
                    (dataset_version_id,),
                ).fetchall()
            }
            unexpected = sorted(roles & OUTPUT_ROLES)
            if unexpected:
                raise RuntimeError(
                    "refusing to overwrite fixture-backed predictive outputs: "
                    + ", ".join(unexpected)
                )
            candidates = _runtime_candidates(connection, dataset_version_id)
            if not candidates:
                raise RuntimeError("canonical V3.1 source ingestion produced no CNC observations")

            existing = connection.execute(
                """
                SELECT COUNT(*) AS count,
                       COUNT(*) FILTER (WHERE model_version=%s) AS current_model_count,
                       COUNT(*) FILTER (
                           WHERE provenance->>'source_type'='product_runtime_inference'
                       ) AS runtime_count
                FROM pm_result_artifacts
                WHERE dataset_version_id=%s
                """,
                (predictor.model_version, dataset_version_id),
            ).fetchone()
            if (
                int(existing["count"] or 0) == len(candidates)
                and int(existing["current_model_count"] or 0) == len(candidates)
                and int(existing["runtime_count"] or 0) == len(candidates)
            ):
                return {
                    "model_version": predictor.model_version,
                    "result_artifact_count": len(candidates),
                    "reused": True,
                }

            # This Dataset Version is source-only by contract, so its runtime
            # outputs can be refreshed atomically without touching gen_data rows.
            connection.execute(
                "DELETE FROM pm_result_artifacts WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                "DELETE FROM pm_prediction_factors WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                "DELETE FROM pm_prediction_timeline WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                "DELETE FROM pm_prediction_snapshots WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                """
                DELETE FROM prediction_results
                WHERE project_id=%s
                  AND payload_json->>'dataset_version_id'=%s
                  AND payload_json->>'source_type'='product_runtime_inference'
                """,
                (PROJECT_ID, dataset_version_id),
            )

            status_counts: dict[str, int] = {}
            for row in candidates:
                artifact = build_product_result_artifact(
                    _runtime_fixture(row),
                    predictor=predictor,
                )
                probability = float(artifact["failure_probability"])
                binary_type = (
                    "failure_risk" if probability >= 0.5 else "no_significant_risk"
                )
                diagnostic_type = str(artifact["predicted_failure_type"])
                provenance = dict(artifact["provenance"])
                provenance.update(
                    {
                        "dataset_version_id": dataset_version_id,
                        "source_version": SOURCE_VERSION,
                        "source_observation_sha256": str(row["source_sha256"]),
                        "diagnostic_failure_type": diagnostic_type,
                    }
                )
                prediction_id = str(provenance["prediction_id"])
                prediction_result_id = f"pmrt-{uuid.uuid5(uuid.NAMESPACE_URL, f'{dataset_version_id}:{prediction_id}')}"
                artifact_checksum = _artifact_checksum({**artifact, "provenance": provenance})
                confidence = float(artifact["confidence"])
                status = str(artifact["status_grade"])
                status_counts[status] = status_counts.get(status, 0) + 1
                feature_scope = [str(item["feature"]) for item in artifact["top_factors"]]
                result_payload = {
                    **artifact,
                    "predicted_failure_type": binary_type,
                    "provenance": provenance,
                    "dataset_version_id": dataset_version_id,
                    "source_type": "product_runtime_inference",
                }

                connection.execute(
                    """
                    INSERT INTO prediction_results(
                        prediction_id,organization_id,project_id,workspace_id,
                        subject_object_type,subject_object_id,prediction_status,
                        model_version,dataset_version,payload_json,created_at,received_at
                    ) VALUES (%s,%s,%s,%s,'equipment',%s,%s,%s,%s,%s,%s,now())
                    """,
                    (
                        prediction_result_id,
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        row["asset_id"],
                        status,
                        predictor.model_version,
                        SOURCE_VERSION,
                        Jsonb(result_payload),
                        row["observed_at"],
                    ),
                )
                connection.execute(
                    """
                    INSERT INTO pm_prediction_snapshots(
                        organization_id,project_id,workspace_id,dataset_version_id,
                        prediction_id,prediction_result_id,asset_id,asset_type,observed_at,
                        prediction_horizon_hours,failure_probability,predicted_failure_type,
                        confidence,status,model_version,feature_scope,source_sha256
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,'cnc',%s,24,%s,%s,%s,%s,%s,%s,%s)
                    """,
                    (
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        dataset_version_id,
                        prediction_id,
                        prediction_result_id,
                        row["asset_id"],
                        row["observed_at"],
                        probability,
                        binary_type,
                        confidence,
                        status,
                        predictor.model_version,
                        Jsonb(feature_scope),
                        artifact_checksum,
                    ),
                )
                for factor in artifact["top_factors"]:
                    signed = float(factor["signed_contribution"])
                    connection.execute(
                        """
                        INSERT INTO pm_prediction_factors(
                            organization_id,project_id,workspace_id,dataset_version_id,
                            prediction_id,rank,feature,feature_value,signed_contribution,
                            absolute_contribution,direction,explanation_method,source_type,source_sha256
                        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,
                                  'product_runtime_inference',%s)
                        """,
                        (
                            ORGANIZATION_ID,
                            PROJECT_ID,
                            WORKSPACE_ID,
                            dataset_version_id,
                            prediction_id,
                            int(factor["rank"]),
                            factor["feature"],
                            float(factor["feature_value"]),
                            signed,
                            abs(signed),
                            factor["direction"],
                            factor["explanation_method"],
                            artifact_checksum,
                        ),
                    )
                connection.execute(
                    """
                    INSERT INTO pm_prediction_timeline(
                        organization_id,project_id,workspace_id,dataset_version_id,
                        prediction_id,asset_id,asset_type,observed_at,
                        prediction_horizon_hours,failure_probability,status,top_factors,
                        model_version,feature_scope,source_type,source_sha256
                    ) VALUES (%s,%s,%s,%s,%s,%s,'cnc',%s,24,%s,%s,%s,%s,%s,
                              'product_runtime_inference',%s)
                    """,
                    (
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        dataset_version_id,
                        prediction_id,
                        row["asset_id"],
                        row["observed_at"],
                        probability,
                        status,
                        Jsonb(artifact["top_factors"]),
                        predictor.model_version,
                        Jsonb(feature_scope),
                        artifact_checksum,
                    ),
                )
                connection.execute(
                    """
                    INSERT INTO pm_result_artifacts(
                        organization_id,project_id,workspace_id,dataset_version_id,
                        artifact_id,prediction_id,prediction_result_id,asset_id,asset_type,
                        observed_at,prediction_horizon_hours,prediction_task,
                        failure_probability,predicted_failure_type,status_grade,confidence,
                        top_factors,recommended_action,provenance,schema_version,
                        model_version,source_sha256
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,'cnc',%s,24,
                              'binary_failure_within_horizon',%s,%s,%s,%s,%s,%s,%s,
                              'result-artifact-v1.0',%s,%s)
                    """,
                    (
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        dataset_version_id,
                        artifact["artifact_id"],
                        prediction_id,
                        prediction_result_id,
                        row["asset_id"],
                        row["observed_at"],
                        probability,
                        binary_type,
                        status,
                        confidence,
                        Jsonb(artifact["top_factors"]),
                        Jsonb(artifact["recommended_action"]),
                        Jsonb(provenance),
                        predictor.model_version,
                        artifact_checksum,
                    ),
                )

            return {
                "model_version": predictor.model_version,
                "result_artifact_count": len(candidates),
                "status_counts": status_counts,
                "reused": False,
            }


def _publish_materialized_version(
    database_url: str,
    *,
    dataset_version_id: str,
    result_artifact_count: int,
) -> None:
    if result_artifact_count < 1:
        raise RuntimeError("refusing to publish a predictive-maintenance version without runtime results")
    psycopg, dict_row, _ = _postgres_modules()
    with psycopg.connect(database_url, row_factory=dict_row) as connection:
        with connection.transaction():
            _set_scope(connection)
            relational = connection.execute(
                """
                SELECT status FROM store_projections
                WHERE dataset_version_id=%s AND store_kind='relational'
                """,
                (dataset_version_id,),
            ).fetchone()
            ingestion = connection.execute(
                """
                SELECT status FROM ontology_ingestion_runs
                WHERE dataset_version_id=%s
                ORDER BY completed_at DESC NULLS LAST
                LIMIT 1
                """,
                (dataset_version_id,),
            ).fetchone()
            if relational is None or relational["status"] != "ready":
                raise RuntimeError("relational projection is not ready")
            if ingestion is None or ingestion["status"] != "completed":
                raise RuntimeError("ontology materialization is not complete")
            connection.execute(
                """
                UPDATE dataset_versions
                SET status='published'
                WHERE id=%s AND organization_id=%s AND project_id=%s
                """,
                (dataset_version_id, ORGANIZATION_ID, PROJECT_ID),
            )


def bootstrap_demo_predictive_maintenance(
    *,
    source_root: str | Path = DEFAULT_SOURCE_ROOT,
    database_url: str | None = None,
) -> dict[str, Any]:
    target = _normalize_database_url(database_url or database_target())
    root = Path(source_root).expanduser().resolve(strict=True)
    manifest = PredictiveMaintenanceCanonicalV3SourceAdapter.build_manifest(
        root,
        organization_id=ORGANIZATION_ID,
        project_id=PROJECT_ID,
        workspace_id=WORKSPACE_ID,
    )
    validator = BundleFileAdapter(allowed_roots=[root])
    validation = validator.validate(manifest)
    if validation.status != "completed":
        issues = [f"{item.role}:{item.code}" for item in validation.issues[:10]]
        raise RuntimeError("Canonical V3.1 source validation failed: " + ", ".join(issues))
    ingestion = PostgreSQLPredictiveMaintenanceBundleIngestor(target).ingest_validated_bundle(
        manifest=manifest,
        validation=validation,
    )
    runtime = _materialize_runtime_results(target, ingestion.dataset_version_id)
    materializer = PredictiveMaintenanceOntologyMaterializer(target)
    materializer.ensure_default_mapping(
        organization_id=ORGANIZATION_ID,
        project_id=PROJECT_ID,
        workspace_id=WORKSPACE_ID,
        dataset_id=ingestion.dataset_id,
        dataset_version_id=ingestion.dataset_version_id,
        approve=True,
        approved_by="render-demo-bootstrap",
    )
    ontology = materializer.materialize(
        organization_id=ORGANIZATION_ID,
        project_id=PROJECT_ID,
        workspace_id=WORKSPACE_ID,
        dataset_id=ingestion.dataset_id,
        dataset_version_id=ingestion.dataset_version_id,
    )
    _publish_materialized_version(
        target,
        dataset_version_id=ingestion.dataset_version_id,
        result_artifact_count=int(runtime["result_artifact_count"]),
    )
    return {
        "source_version": SOURCE_VERSION,
        "dataset_id": ingestion.dataset_id,
        "dataset_version_id": ingestion.dataset_version_id,
        "source_bundle_reused": ingestion.reused_dataset_version,
        "source_row_counts": ingestion.row_counts,
        "runtime": runtime,
        "ontology": ontology.model_dump(mode="json"),
        "published": True,
    }


def main() -> int:
    source_root = os.getenv("ONTOLOGY_DASHBOARD_DEMO_SOURCE_ROOT", str(DEFAULT_SOURCE_ROOT))
    payload = bootstrap_demo_predictive_maintenance(source_root=source_root)
    print(json.dumps(payload, ensure_ascii=False, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
