"""Idempotent Canonical V3.1 bootstrap for the hosted demo environment.

The source snapshot is produced by ``Biz-CollabCraft/gen_data`` and contains
only canonical source/reference material needed for ingestion. Prediction and
Result Artifact fixtures from gen_data are deliberately not consumed here.
Product results are generated by backend diagnosis runtime inference.
"""

from __future__ import annotations

import hashlib
import json
import os
import uuid
from pathlib import Path
from typing import Any

from app.diagnosis.evidence import build_product_result_artifact
from app.diagnosis.predictor import HeuristicPredictor, configured_predictor

from app.dataset.ingestion import (
    BundleFileAdapter,
    PredictiveMaintenanceCanonicalV3SourceAdapter,
)
from app.infra.db.postgresql_bundle_ingestion import PostgreSQLPredictiveMaintenanceBundleIngestor
from .dependencies import database_target
from .domain_packs.predictive_maintenance import PredictiveMaintenanceOntologyMaterializer


ORGANIZATION_ID = "org-ontology-demo"
PROJECT_ID = "manufacturing-demo-project"
WORKSPACE_ID = "manufacturing-demo"
SOURCE_VERSION = "canonical-ai4i-physics-v3.1"
RUNTIME_SELECTION_STRATEGY = "latest_observation_per_asset_v1"
RUNTIME_MATERIALIZATION_PROFILE = "cnc_heuristic_compressor_artifact_current_state_v2"
DEFAULT_SOURCE_ROOT = Path("/app/.source/gen_data")
OUTPUT_ROLES = {
    "prediction_snapshot",
    "prediction_factor",
    "prediction_timeline",
    "result_artifact",
}


def _postgres_modules():
    try:
        import psycopg
        from psycopg.rows import dict_row
        from psycopg.types.json import Jsonb
    except ImportError as exc:  # pragma: no cover - deployment packaging guard
        raise RuntimeError("demo predictive-maintenance bootstrap requires backend[postgres]") from exc
    return psycopg, dict_row, Jsonb


def _normalize_database_url(value: str) -> str:
    normalized = value.replace("postgresql+psycopg://", "postgresql://", 1)
    if not normalized.startswith("postgresql://"):
        raise ValueError("hosted predictive-maintenance bootstrap requires PostgreSQL")
    return normalized


def _set_scope(connection: Any) -> None:
    connection.execute("SELECT set_config('app.organization_id',%s,true)", (ORGANIZATION_ID,))
    connection.execute("SELECT set_config('app.project_id',%s,true)", (PROJECT_ID,))


def _runtime_candidates(connection: Any, dataset_version_id: str) -> list[dict[str, Any]]:
    """Select the latest observation for every canonical equipment asset.

    The MVP overview represents the latest known state of both canonical asset
    families (CNC and compressor). Historical warning/critical observations remain
    in source data and belong in event/history views rather than replacing current
    state.
    """

    return list(
        connection.execute(
            """
            WITH cnc_ranked AS (
                SELECT o.*,
                       ROW_NUMBER() OVER (PARTITION BY o.asset_id ORDER BY o.observed_at DESC) AS row_number
                FROM pm_cnc_observations o
                WHERE o.dataset_version_id=%s
            ), latest_cnc AS (
                SELECT o.asset_id,o.observed_at,o.source_sha256,'cnc'::text AS asset_type,
                       jsonb_build_object(
                           'product_type',o.product_type,
                           'air_temperature_k',o.air_temperature_k,
                           'process_temperature_k',o.process_temperature_k,
                           'rotational_speed_rpm',o.rotational_speed_rpm,
                           'torque_nm',o.torque_nm,
                           'tool_wear_min',o.tool_wear_min
                       ) AS observation,
                       COALESCE(
                           (
                               SELECT jsonb_agg(
                                   jsonb_build_object(
                                       'timestamp',h.observed_at,
                                       'product_type',h.product_type,
                                       'air_temperature_k',h.air_temperature_k,
                                       'process_temperature_k',h.process_temperature_k,
                                       'rotational_speed_rpm',h.rotational_speed_rpm,
                                       'torque_nm',h.torque_nm,
                                       'tool_wear_min',h.tool_wear_min
                                   ) ORDER BY h.observed_at ASC
                               )
                               FROM cnc_ranked h
                               WHERE h.asset_id=o.asset_id AND h.observed_at < o.observed_at
                           ),
                           '[]'::jsonb
                       ) AS history
                FROM cnc_ranked o
                WHERE o.row_number=1
            ), compressor_ranked AS (
                SELECT o.*,
                       ROW_NUMBER() OVER (PARTITION BY o.asset_id ORDER BY o.observed_at DESC) AS row_number
                FROM pm_compressor_observations o
                WHERE o.dataset_version_id=%s
            ), latest_compressor AS (
                SELECT o.asset_id,o.observed_at,o.source_sha256,'compressor'::text AS asset_type,
                       jsonb_build_object(
                           'voltage_raw',o.voltage_raw,
                           'rotation_raw',o.rotation_raw,
                           'pressure_raw',o.pressure_raw,
                           'vibration_raw',o.vibration_raw,
                           'relative_vibration_z',o.relative_vibration_z,
                           'relative_vibration_zone',o.relative_vibration_zone
                       ) AS observation,
                       COALESCE(
                           (
                               SELECT jsonb_agg(
                                   jsonb_build_object(
                                       'timestamp',h.observed_at,
                                       'voltage_raw',h.voltage_raw,
                                       'rotation_raw',h.rotation_raw,
                                       'pressure_raw',h.pressure_raw,
                                       'vibration_raw',h.vibration_raw,
                                       'relative_vibration_z',h.relative_vibration_z,
                                       'relative_vibration_zone',h.relative_vibration_zone
                                   ) ORDER BY h.observed_at ASC
                               )
                               FROM compressor_ranked h
                               WHERE h.asset_id=o.asset_id AND h.observed_at < o.observed_at
                           ),
                           '[]'::jsonb
                       ) AS history
                FROM compressor_ranked o
                WHERE o.row_number=1
            )
            SELECT * FROM latest_cnc
            UNION ALL
            SELECT * FROM latest_compressor
            ORDER BY asset_id
            """,
            (dataset_version_id, dataset_version_id),
        ).fetchall()
    )


def _artifact_checksum(artifact: dict[str, Any]) -> str:
    rendered = json.dumps(
        artifact,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(rendered).hexdigest()


def _compressor_runtime_history(
    connection: Any,
    dataset_version_id: str,
    asset_id: str,
    observed_at: Any,
) -> list[dict[str, Any]]:
    """Return the 35 observations immediately preceding compressor inference."""

    rows = connection.execute(
        """
        SELECT observed_at,voltage_raw,rotation_raw,pressure_raw,vibration_raw,
               relative_vibration_z,relative_vibration_zone
        FROM pm_compressor_observations
        WHERE dataset_version_id=%s AND asset_id=%s AND observed_at < %s
        ORDER BY observed_at DESC
        LIMIT 35
        """,
        (dataset_version_id, asset_id, observed_at),
    ).fetchall()
    ordered = list(reversed(rows))
    return [
        {
            "timestamp": item["observed_at"].isoformat(),
            "voltage_raw": float(item["voltage_raw"]),
            "rotation_raw": float(item["rotation_raw"]),
            "pressure_raw": float(item["pressure_raw"]),
            "vibration_raw": float(item["vibration_raw"]),
            "relative_vibration_z": float(item["relative_vibration_z"]),
            "relative_vibration_zone": str(item["relative_vibration_zone"]),
        }
        for item in ordered
    ]


def _runtime_fixture(row: dict[str, Any], *, history: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    observed_at = row["observed_at"].isoformat()
    asset_id = str(row["asset_id"])
    asset_type = str(row["asset_type"])
    source = dict(row["observation"])
    if asset_type == "compressor":
        observation = {
            "timestamp": observed_at,
            "voltage_raw": float(source["voltage_raw"]),
            "rotation_raw": float(source["rotation_raw"]),
            "pressure_raw": float(source["pressure_raw"]),
            "vibration_raw": float(source["vibration_raw"]),
            "relative_vibration_z": float(source["relative_vibration_z"]),
            "relative_vibration_zone": str(source["relative_vibration_zone"]),
        }
    else:
        observation = {
            "timestamp": observed_at,
            "product_type": source.get("product_type"),
            "air_temperature_k": float(source["air_temperature_k"]),
            "process_temperature_k": float(source["process_temperature_k"]),
            "rotational_speed_rpm": float(source["rotational_speed_rpm"]),
            "torque_nm": float(source["torque_nm"]),
            "tool_wear_min": float(source["tool_wear_min"]),
        }
    return {
        "schema_version": "1.0",
        "event_id": f"runtime-{asset_id}-{observed_at}",
        "scenario_id": f"canonical-v3.1-runtime:{asset_id}",
        "dataset_version": SOURCE_VERSION,
        "asset_type": asset_type,
        "equipment": {
            "equipment_id": asset_id,
            # Source asset_master has no business criticality. Keep inference
            # neutral; product UI derives display criticality from result status.
            "criticality": "medium",
        },
        "observation": observation,
        "history": list(history if history is not None else row.get("history") or []),
    }


def _materialize_runtime_results(database_url: str, dataset_version_id: str) -> dict[str, Any]:
    psycopg, dict_row, Jsonb = _postgres_modules()
    # The active Model Artifact is currently compressor-specific. Keep the CNC
    # deterministic compatibility predictor isolated until a CNC artifact is
    # published rather than applying a compressor artifact to CNC fields.
    cnc_predictor = HeuristicPredictor()
    compressor_predictor = configured_predictor()
    with psycopg.connect(database_url, row_factory=dict_row) as connection:
        with connection.transaction():
            _set_scope(connection)
            connection.execute(
                "SELECT pg_advisory_xact_lock(hashtext(%s))",
                (f"demo-runtime:{PROJECT_ID}:{dataset_version_id}",),
            )
            roles = {
                str(row["role"])
                for row in connection.execute(
                    "SELECT role FROM dataset_files WHERE dataset_version_id=%s",
                    (dataset_version_id,),
                ).fetchall()
            }
            unexpected = sorted(roles & OUTPUT_ROLES)
            if unexpected:
                raise RuntimeError(
                    "refusing to overwrite fixture-backed predictive outputs: "
                    + ", ".join(unexpected)
                )
            candidates = _runtime_candidates(connection, dataset_version_id)
            if not candidates:
                raise RuntimeError("canonical V3.1 source ingestion produced no equipment observations")

            existing = connection.execute(
                """
                SELECT COUNT(*) AS count,
                       COUNT(*) FILTER (
                           WHERE provenance->>'source_type'='product_runtime_inference'
                       ) AS runtime_count,
                       COUNT(*) FILTER (
                           WHERE provenance->>'selection_strategy'=%s
                       ) AS current_selection_count,
                       COUNT(*) FILTER (
                           WHERE provenance->>'materialization_profile'=%s
                       ) AS current_profile_count
                FROM pm_result_artifacts
                WHERE dataset_version_id=%s
                """,
                (
                    RUNTIME_SELECTION_STRATEGY,
                    RUNTIME_MATERIALIZATION_PROFILE,
                    dataset_version_id,
                ),
            ).fetchone()
            if (
                int(existing["count"] or 0) == len(candidates)
                and int(existing["runtime_count"] or 0) == len(candidates)
                and int(existing["current_selection_count"] or 0) == len(candidates)
                and int(existing["current_profile_count"] or 0) == len(candidates)
            ):
                return {
                    "model_versions": sorted({cnc_predictor.model_version, compressor_predictor.model_version}),
                    "result_artifact_count": len(candidates),
                    "selection_strategy": RUNTIME_SELECTION_STRATEGY,
                    "materialization_profile": RUNTIME_MATERIALIZATION_PROFILE,
                    "reused": True,
                }

            # This Dataset Version is source-only by contract, so its runtime
            # outputs can be refreshed atomically without touching gen_data rows.
            connection.execute(
                "DELETE FROM pm_result_artifacts WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                "DELETE FROM pm_prediction_factors WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                "DELETE FROM pm_prediction_timeline WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                "DELETE FROM pm_prediction_snapshots WHERE dataset_version_id=%s",
                (dataset_version_id,),
            )
            connection.execute(
                """
                DELETE FROM prediction_results
                WHERE project_id=%s
                  AND payload_json->>'dataset_version_id'=%s
                  AND payload_json->>'source_type'='product_runtime_inference'
                """,
                (PROJECT_ID, dataset_version_id),
            )

            status_counts: dict[str, int] = {}
            asset_type_counts: dict[str, int] = {}
            for row in candidates:
                asset_type = str(row["asset_type"])
                predictor = compressor_predictor if asset_type == "compressor" else cnc_predictor
                history = (
                    _compressor_runtime_history(
                        connection,
                        dataset_version_id,
                        str(row["asset_id"]),
                        row["observed_at"],
                    )
                    if asset_type == "compressor"
                    else []
                )
                artifact = build_product_result_artifact(
                    _runtime_fixture(row, history=history),
                    predictor=predictor,
                )
                probability = float(artifact["failure_probability"])
                diagnostic_type = str(artifact["predicted_failure_type"])
                if asset_type == "compressor" and diagnostic_type in {"failure_risk", "none"}:
                    binary_type = (
                        "failure_risk" if diagnostic_type == "failure_risk" else "no_significant_risk"
                    )
                else:
                    binary_type = (
                        "failure_risk" if probability >= 0.5 else "no_significant_risk"
                    )
                provenance = dict(artifact["provenance"])
                provenance.update(
                    {
                        "dataset_version_id": dataset_version_id,
                        "source_version": SOURCE_VERSION,
                        "source_observation_sha256": str(row["source_sha256"]),
                        "diagnostic_failure_type": diagnostic_type,
                        "selection_strategy": RUNTIME_SELECTION_STRATEGY,
                        "materialization_profile": RUNTIME_MATERIALIZATION_PROFILE,
                    }
                )
                prediction_id = str(provenance["prediction_id"])
                prediction_result_id = f"pmrt-{uuid.uuid5(uuid.NAMESPACE_URL, f'{dataset_version_id}:{prediction_id}')}"
                artifact_checksum = _artifact_checksum({**artifact, "provenance": provenance})
                confidence = float(artifact["confidence"])
                status = str(artifact["status_grade"])
                status_counts[status] = status_counts.get(status, 0) + 1
                asset_type_counts[asset_type] = asset_type_counts.get(asset_type, 0) + 1
                feature_scope = [str(item["feature"]) for item in artifact["top_factors"]]
                result_payload = {
                    **artifact,
                    "predicted_failure_type": binary_type,
                    "provenance": provenance,
                    "dataset_version_id": dataset_version_id,
                    "source_type": "product_runtime_inference",
                }

                connection.execute(
                    """
                    INSERT INTO prediction_results(
                        prediction_id,organization_id,project_id,workspace_id,
                        subject_object_type,subject_object_id,prediction_status,
                        model_version,dataset_version,payload_json,created_at,received_at
                    ) VALUES (%s,%s,%s,%s,'equipment',%s,%s,%s,%s,%s,%s,now())
                    """,
                    (
                        prediction_result_id,
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        row["asset_id"],
                        status,
                        artifact["provenance"]["model_version"],
                        SOURCE_VERSION,
                        Jsonb(result_payload),
                        row["observed_at"],
                    ),
                )
                connection.execute(
                    """
                    INSERT INTO pm_prediction_snapshots(
                        organization_id,project_id,workspace_id,dataset_version_id,
                        prediction_id,prediction_result_id,asset_id,asset_type,observed_at,
                        prediction_horizon_hours,failure_probability,predicted_failure_type,
                        confidence,status,model_version,feature_scope,source_sha256
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,24,%s,%s,%s,%s,%s,%s,%s)
                    """,
                    (
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        dataset_version_id,
                        prediction_id,
                        prediction_result_id,
                        row["asset_id"],
                        asset_type,
                        row["observed_at"],
                        probability,
                        binary_type,
                        confidence,
                        status,
                        artifact["provenance"]["model_version"],
                        Jsonb(feature_scope),
                        artifact_checksum,
                    ),
                )
                for factor in artifact["top_factors"]:
                    signed = float(factor["signed_contribution"])
                    connection.execute(
                        """
                        INSERT INTO pm_prediction_factors(
                            organization_id,project_id,workspace_id,dataset_version_id,
                            prediction_id,rank,feature,feature_value,signed_contribution,
                            absolute_contribution,direction,explanation_method,source_type,source_sha256
                        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,
                                  'product_runtime_inference',%s)
                        """,
                        (
                            ORGANIZATION_ID,
                            PROJECT_ID,
                            WORKSPACE_ID,
                            dataset_version_id,
                            prediction_id,
                            int(factor["rank"]),
                            factor["feature"],
                            float(factor["feature_value"]),
                            signed,
                            abs(signed),
                            factor["direction"],
                            factor["explanation_method"],
                            artifact_checksum,
                        ),
                    )
                connection.execute(
                    """
                    INSERT INTO pm_prediction_timeline(
                        organization_id,project_id,workspace_id,dataset_version_id,
                        prediction_id,asset_id,asset_type,observed_at,
                        prediction_horizon_hours,failure_probability,status,top_factors,
                        model_version,feature_scope,source_type,source_sha256
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,24,%s,%s,%s,%s,%s,
                              'product_runtime_inference',%s)
                    """,
                    (
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        dataset_version_id,
                        prediction_id,
                        row["asset_id"],
                        asset_type,
                        row["observed_at"],
                        probability,
                        status,
                        Jsonb(artifact["top_factors"]),
                        artifact["provenance"]["model_version"],
                        Jsonb(feature_scope),
                        artifact_checksum,
                    ),
                )
                connection.execute(
                    """
                    INSERT INTO pm_result_artifacts(
                        organization_id,project_id,workspace_id,dataset_version_id,
                        artifact_id,prediction_id,prediction_result_id,asset_id,asset_type,
                        observed_at,prediction_horizon_hours,prediction_task,
                        failure_probability,predicted_failure_type,status_grade,confidence,
                        top_factors,recommended_action,provenance,schema_version,
                        model_version,source_sha256
                    ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,24,
                              'binary_failure_within_horizon',%s,%s,%s,%s,%s,%s,%s,
                              'result-artifact-v1.0',%s,%s)
                    """,
                    (
                        ORGANIZATION_ID,
                        PROJECT_ID,
                        WORKSPACE_ID,
                        dataset_version_id,
                        artifact["artifact_id"],
                        prediction_id,
                        prediction_result_id,
                        row["asset_id"],
                        asset_type,
                        row["observed_at"],
                        probability,
                        binary_type,
                        status,
                        confidence,
                        Jsonb(artifact["top_factors"]),
                        Jsonb(artifact["recommended_action"]),
                        Jsonb(provenance),
                        artifact["provenance"]["model_version"],
                        artifact_checksum,
                    ),
                )

            return {
                "model_versions": sorted({cnc_predictor.model_version, compressor_predictor.model_version}),
                "result_artifact_count": len(candidates),
                "status_counts": status_counts,
                "asset_type_counts": asset_type_counts,
                "selection_strategy": RUNTIME_SELECTION_STRATEGY,
                "materialization_profile": RUNTIME_MATERIALIZATION_PROFILE,
                "reused": False,
            }


def _publish_materialized_version(
    database_url: str,
    *,
    dataset_version_id: str,
    result_artifact_count: int,
) -> None:
    if result_artifact_count < 1:
        raise RuntimeError("refusing to publish a predictive-maintenance version without runtime results")
    psycopg, dict_row, _ = _postgres_modules()
    with psycopg.connect(database_url, row_factory=dict_row) as connection:
        with connection.transaction():
            _set_scope(connection)
            relational = connection.execute(
                """
                SELECT status FROM store_projections
                WHERE dataset_version_id=%s AND store_kind='relational'
                """,
                (dataset_version_id,),
            ).fetchone()
            ingestion = connection.execute(
                """
                SELECT status FROM ontology_ingestion_runs
                WHERE dataset_version_id=%s
                ORDER BY completed_at DESC NULLS LAST
                LIMIT 1
                """,
                (dataset_version_id,),
            ).fetchone()
            if relational is None or relational["status"] != "ready":
                raise RuntimeError("relational projection is not ready")
            if ingestion is None or ingestion["status"] != "completed":
                raise RuntimeError("ontology materialization is not complete")
            connection.execute(
                """
                UPDATE dataset_versions
                SET status='published'
                WHERE id=%s AND organization_id=%s AND project_id=%s
                """,
                (dataset_version_id, ORGANIZATION_ID, PROJECT_ID),
            )


def bootstrap_demo_predictive_maintenance(
    *,
    source_root: str | Path = DEFAULT_SOURCE_ROOT,
    database_url: str | None = None,
) -> dict[str, Any]:
    target = _normalize_database_url(database_url or database_target())
    root = Path(source_root).expanduser().resolve(strict=True)
    manifest = PredictiveMaintenanceCanonicalV3SourceAdapter.build_manifest(
        root,
        organization_id=ORGANIZATION_ID,
        project_id=PROJECT_ID,
        workspace_id=WORKSPACE_ID,
    )
    validator = BundleFileAdapter(allowed_roots=[root])
    validation = validator.validate(manifest)
    if validation.status != "completed":
        issues = [f"{item.role}:{item.code}" for item in validation.issues[:10]]
        raise RuntimeError("Canonical V3.1 source validation failed: " + ", ".join(issues))
    ingestion = PostgreSQLPredictiveMaintenanceBundleIngestor(target).ingest_validated_bundle(
        manifest=manifest,
        validation=validation,
    )
    runtime = _materialize_runtime_results(target, ingestion.dataset_version_id)
    materializer = PredictiveMaintenanceOntologyMaterializer(target)
    materializer.ensure_default_mapping(
        organization_id=ORGANIZATION_ID,
        project_id=PROJECT_ID,
        workspace_id=WORKSPACE_ID,
        dataset_id=ingestion.dataset_id,
        dataset_version_id=ingestion.dataset_version_id,
        approve=True,
        approved_by="render-demo-bootstrap",
    )
    ontology = materializer.materialize(
        organization_id=ORGANIZATION_ID,
        project_id=PROJECT_ID,
        workspace_id=WORKSPACE_ID,
        dataset_id=ingestion.dataset_id,
        dataset_version_id=ingestion.dataset_version_id,
    )
    _publish_materialized_version(
        target,
        dataset_version_id=ingestion.dataset_version_id,
        result_artifact_count=int(runtime["result_artifact_count"]),
    )
    return {
        "source_version": SOURCE_VERSION,
        "dataset_id": ingestion.dataset_id,
        "dataset_version_id": ingestion.dataset_version_id,
        "source_bundle_reused": ingestion.reused_dataset_version,
        "source_row_counts": ingestion.row_counts,
        "runtime": runtime,
        "ontology": ontology.model_dump(mode="json"),
        "published": True,
    }


def main() -> int:
    source_root = os.getenv("ONTOLOGY_DASHBOARD_DEMO_SOURCE_ROOT", str(DEFAULT_SOURCE_ROOT))
    payload = bootstrap_demo_predictive_maintenance(source_root=source_root)
    print(json.dumps(payload, ensure_ascii=False, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
