import {describe,it,expect} from 'vitest';
import {mapPresentation,feature,date,label,text,message} from './presentation.js';
const base=()=>({reqQueue:[],isPlan:true,kpis:[],artifactLine:'RESULT#keep',shaLine:'sha256:keep'});
const state=()=>({detail:{event:{status:'critical',failureProbability:0.78},snapshotBasis:{observedAt:'2026-08-29T14:00:00Z'},sensors:[],topFactors:[],warnings:[],operationContext:{},maintenanceContext:{}},model:{context:{}},lineage:{work_orders:[]}});
describe('field mappings and Korean field labels',()=>{
 it('translates display labels without rewriting source IDs',()=>{expect(feature('rotation_raw_6h_std')).toBe('회전 신호 · 6시간 변동폭(표준편차)');expect(label('process_manager')).toBe('생산관리자');expect(text('Production Reliability')).toBe('생산 설비 관리');expect(text('CNC-S01-L01-01')).toBe('CNC-S01-L01-01');expect(date('2026-08-29T14:00:00Z')).toContain('23:00');const v=mapPresentation(base(),state());expect(v.artifactLine).toBe('RESULT#keep');expect(v.selGrade).toBe('긴급 확인');});
 it('shows actual history with timestamp and does not invent current samples or units',()=>{const s=state();s.detail.sensors=[{id:'voltage_raw',value:null,unit:null,historyPoints:[{value:10,observedAt:'2026-08-29T13:50:00Z'},{value:20,observedAt:'2026-08-29T14:00:00Z'}]}];const v=mapPresentation(base(),s);expect(v.signals[0]).toMatchObject({label:'전압',value:'20',unit:'단위 미제공'});expect(v.signals[0].bars).toHaveLength(2);expect(v.signals[0].state).toContain('최근 관측');expect(s.detail.sensors[0].value).toBeNull();});
 it('binds available scoped production plans and zero values',()=>{const s=state();s.contextRead={domains:{planning:{context:{status:'available',data:{production_plan:{planned_units:0,product_mix:[{variant:'A',planned_units:0}]}}}}}};const v=mapPresentation(base(),s);expect(v.kpis[0].value).toBe('0');expect(v.variants[0].plan).toBe('0');expect(v.shifts[0].made).toBe('실적 자료 없음');});
 it('withholds unavailable planning data and preserves read failure',()=>{const s=state();s.contextRead={domains:{planning:{context:{status:'stale',data:{production_plan:{planned_units:999}}}}}};s.contextError='404 · not_found';const v=mapPresentation(base(),s);expect(v.kpis).toEqual([]);expect(v.gaps[0].reason).toContain('404');});
 it('shows conditional impact without treating it as realized loss',()=>{const s=state();s.contextRead={production_impact:{options:[{option:'stop_now',state:'calculated',remaining_exposed_units:15},{option:'continue_operation',state:'not_calculable',remaining_exposed_units:999}]}};const v=mapPresentation(base(),s);expect(v.opCtx.find(r=>r.label==='즉시 정지 · 잔여 차질').value).toBe('15개 (조건부 예상)');expect(v.opCtx.find(r=>r.label==='운전 지속 · 잔여 차질').value).toBe('계산 조건 미등록');});
 it('labels synthetic production impact as a demo assumption',()=>{const s=state();s.detail.operationContext={productionImpact:'high'};s.contextRead={domains:{planning:{provenance:{source_classification:'synthetic_demo_context'},context:{status:'available',data:{production_plan:{planned_units:10,product_mix:[]}}}}}};const v=mapPresentation(base(),s);expect(v.opCtx.find(r=>r.label==='생산 영향').value).toContain('데모 가정 기준');});
 it('binds persisted workflow and keeps logit contributions numeric',()=>{const s=state();s.lineage.work_orders=[{work_type:'inspection',status:'approved'}];s.detail.topFactors=[{feature:'rotation_raw_6h_mean',value:1,contribution:1.065,direction:'risk_up'}];const v=mapPresentation(base(),s);expect(v.steps[0].mark).toBe('승인됨');expect(v.detailSignals[0].contribVal).toBe('1.065');expect(v.detailSignals[0].contribPct).toBe('100%');});
});

it('reports only the missing maintenance field',()=>{expect(message('maintenance: maintenance_context.similar_events_30d - maintenance_context_missing_or_unresolved')).toBe('최근 30일 유사 사례 집계가 연결되지 않았습니다.');expect(message('operations: operation_context.runtime_hours_7d - operation_context_missing_or_unresolved')).toBe('최근 7일 가동시간 집계가 연결되지 않았습니다.');});
it('shows server state totals and policy without deriving grades',()=>{const s=state();s.factoryRecords={status:'available',total:100,counts:{running:92,stopped:5,maintenance:3,unknown:0},policy:{action_threshold:0.6,attention_threshold:0.3,version:'v1'}};const v=mapPresentation({...base(),isPlan:false,isShift:true,kpis:[{},{},{}]},s);expect(v.kpis[1].value).toBe('92');expect(v.warnValLabel).toBe('0.6');expect(v.attnValLabel).toBe('0.3');expect(v.selGrade).toBe('긴급 확인');});
