from typing import Any, Protocol


class OperationalAssetRegistryPort(Protocol):
    def reconcile(self, snapshot: dict[str, Any]) -> dict[str, Any]: ...
    def list_assets(
        self, *, asset_type: str | None, registry_status: str | None,
        validation_status: str | None, active: bool | None, search: str | None,
        limit: int, offset: int,
    ) -> tuple[list[dict[str, Any]], int]: ...
    def get_asset(self, asset_id: str) -> dict[str, Any] | None: ...
    def list_versions(self, asset_id: str) -> list[dict[str, Any]]: ...
    def latest_reconciliation(self) -> dict[str, Any] | None: ...
    def resolve_dependency(self, asset_type: str, asset_key: str, version: str) -> dict[str, Any] | None: ...


class OperationalAssetInventoryPort(Protocol):
    def fetch_inventory(self) -> dict[str, Any]: ...
