// Browser fault injection against the local replay screen; does not measure live DB reliability.
import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=process.env.DEMO_REPO||path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const {chromium,expect}=createRequire(root+'/systems/frontend/package.json')('@playwright/test');
const b=await chromium.launch();const results=[];const base='http://127.0.0.1:3318/demo-briefing.html';const api='**/api/demo-briefing/cases/*/validate';
async function test(name,fn){const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p);expect(errors).toEqual([]);results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message,errors});}finally{await p.close();}}
const go=async p=>{await p.goto(base);await expect(p.getByRole('button',{name:'브리핑 검증',exact:true})).toBeEnabled();};
const run=p=>p.getByRole('button',{name:'브리핑 검증',exact:true}).click();const confirm=p=>p.getByRole('button',{name:'근거를 읽고 확인',exact:true});
const ready=p=>expect(p.locator('.natural-briefing-line').first()).toBeVisible();
await test('연속 클릭 중복 요청 방지',async p=>{let count=0;await p.route(api,async r=>{count++;const response=await r.fetch();await new Promise(r=>setTimeout(r,700));await r.fulfill({response});});await go(p);await p.getByRole('button',{name:'브리핑 검증',exact:true}).evaluate(e=>{for(let i=0;i<20;i++)e.click();});await ready(p);expect(count).toBe(1);});
await test('늦은 검증 응답과 사례 전환',async p=>{await p.route(api,async r=>{const response=await r.fetch();await new Promise(r=>setTimeout(r,900));await r.fulfill({response}).catch(()=>{});});await go(p);await run(p);await p.getByLabel('입력 사례').selectOption('4');await expect(p.locator('.engineer-evidence-summary')).toContainText('CNC-S01-L04-03');await p.waitForTimeout(1100);await expect(p.locator('.natural-briefing-line')).toHaveCount(0);await expect(confirm(p)).toBeDisabled();await run(p);await ready(p);});
await test('검증 연결 실패 후 재시도',async p=>{await go(p);await run(p);await ready(p);await p.route(api,r=>r.abort());await run(p);await expect(p.locator('.final-demo-actions')).toContainText('다시 검사');await expect(p.locator('.natural-briefing-line')).toHaveCount(0);await expect(confirm(p)).toBeDisabled();await p.unroute(api);await run(p);await ready(p);});
await test('서버 503 후 재시도',async p=>{await go(p);await p.route(api,r=>r.fulfill({status:503,body:'unavailable'}));await run(p);await expect(p.locator('.final-demo-actions')).toContainText('다시 검사');await expect(confirm(p)).toBeDisabled();await p.unroute(api);await run(p);await ready(p);});
for(const kind of ['wrong-hash','wrong-asset','pending-status','null-summary'])await test('응답 불일치 차단 '+kind,async p=>{await go(p);await p.route(api,async r=>{const response=await r.fetch();const j=await response.json();if(kind==='wrong-hash')j.replay.input_sha256='other';if(kind==='wrong-asset')j.summary.asset_id='OTHER';if(kind==='pending-status')j.trace.materialization.status='pending';if(kind==='null-summary')j.summary=null;await r.fulfill({response,json:j});});await run(p);await expect(p.locator('.final-demo-actions')).toContainText('다시 검사');await expect(confirm(p)).toBeDisabled();await expect(p.locator('.natural-briefing-line')).toHaveCount(0);});
await test('잘못된 입력 응답에서 화면 유지',async p=>{await p.route('**/api/demo-briefing/cases/3',r=>r.fulfill({json:{case_id:3}}));await p.goto(base);await expect(p.locator('.final-demo-empty')).toContainText('연결하지 못했습니다');await expect(confirm(p)).toBeDisabled();});
await test('새로고침 후 읽음 상태 초기화',async p=>{await go(p);await run(p);await ready(p);await confirm(p).click();await p.reload();await expect(confirm(p)).toBeDisabled();await expect(p.locator('.natural-briefing-line')).toHaveCount(0);});
await test('10초 무응답 종료와 재시도',async p=>{await go(p);await p.route(api,async r=>{await new Promise(r=>setTimeout(r,11500));await r.abort().catch(()=>{});});await run(p);await expect(p.locator('.final-demo-actions')).toContainText('다시 검사',{timeout:12000});await expect(confirm(p)).toBeDisabled();await p.unroute(api);await run(p);await ready(p);});
await test('입력 조회 연결 실패와 복구',async p=>{await p.route('**/api/demo-briefing/cases/3',r=>r.abort());await p.goto(base);await expect(p.locator('.final-demo-empty')).toContainText('연결하지 못했습니다');await expect(confirm(p)).toBeDisabled();await p.unroute('**/api/demo-briefing/cases/3');await p.reload();await run(p);await ready(p);});
await test('사례 30회 연속 전환 후 마지막 입력만 유지',async p=>{await go(p);for(let i=0;i<30;i++)await p.getByLabel('입력 사례').selectOption(String(i%8+1));await expect(p.getByRole('button',{name:'브리핑 검증',exact:true})).toBeEnabled();await expect(p.getByLabel('입력 사례')).toHaveValue('6');await run(p);await ready(p);await expect(p.locator('.final-demo-records')).toContainText('제외');await expect(confirm(p)).toBeEnabled();});
for(const width of [1280,1440,1920])await test('발표 화면 너비 '+width,async p=>{await p.setViewportSize({width,height:720});await go(p);await run(p);await ready(p);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await p.locator('.natural-briefing').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);});
await b.close();fs.writeFileSync('/private/tmp/briefing-stability-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
